debug: false
uuid: d8dbee7b-44c9-4b42-97f5-418d98968a03
token_id: sHIKRLq5KMGu8uw2
token: dWPk2ciALfqv3st9IHvtsULjGkVWKXzzumOdTEaZ9DmEgWxOU1DApgZEjmnx7N5n
api:
  host: 0.0.0.0
  port: 8080
  ssl:
    enabled: false
    cert: /etc/letsencrypt/live/142.132.142.57/fullchain.pem
    key: /etc/letsencrypt/live/142.132.142.57/privkey.pem
  upload_limit: 100
system:
  data: /var/lib/pterodactyl/volumes
  sftp:
    bind_port: 2022
allowed_mounts: []
remote: 'http://royal-morning-13054381.eu-ws3.runcode.io'
